### ISSUE TITLE
Bug running it along with mocha. Potential newbie issue

### ISSUE THREAD

**Issue by rxaviers** [adammck/minitest-pretty_diff#3]
Hi, for some reason I get the following failure when trying to run `rake test` after having added your gem to Gemfile and installed it with `bundle install`:

```
$ rake test
rake aborted!
NameError: uninitialized constant MiniTest::Assertion
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/mocha-1.1.0/lib/mocha/integration/mini_test/adapter.rb:27:in `included'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/mocha-1.1.0/lib/mocha/integration/mini_test.rb:43:in `include'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/mocha-1.1.0/lib/mocha/integration/mini_test.rb:43:in `activate'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/mocha-1.1.0/lib/mocha/mini_test.rb:3:in `<top (required)>'
{omitted_root}/test/test_helper.rb:12:in `<top (required)>'
{omitted_root}/test/controllers/items_controller_test.rb:1:in `require'
{omitted_root}/test/controllers/items_controller_test.rb:1:in `<top (required)>'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `require'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `each'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:113:in `each'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
{omitted_root}/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
```

It seems like it doesn't like `gem 'mocha'` (I'm using version `'1.1.0'`). By the way, `test/test_helper.rb:12` has this code `require 'mocha/mini_test'`.

I apologize in advance for filing this issue with so few info. I'm just wondering if for some reason there's a clear evidence I'm doing something stupid? Thanks

**Comment by adammck** [comment]
I'm sorry, but this gem is quite old and not really maintained any more. I expect that the ecosystem has moved on, and either the MiniTest or Mocha API has changed such that this gem no longer works. I'd be glad to accept a PR to fix this problem, but can't look into it myself.

**Comment by rxaviers** [comment]
Thanks
